service: mm-sign-in
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: somevalue
  stage: dev
  region: us-west-1
  deploymentBucket: picaggo-api-repository
  iam:
    role: arn:aws:iam::somevalue:role/lambda_basic_execution
  layers:
    - arn:aws:lambda:us-west-1:somevalue:layer:mm_utilsLayer:1
    - arn:aws:lambda:us-west-1:somevalue:layer:MediaFileUtils:6

functions:
  SignIn:
    handler: index.handler
    events:
     - httpApi:
         path: /sign-in
         method: post
